grafana:
  service:
    type: NodePort
    nodePort: 30000
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.monitoring:3100
      version: 1

prometheus:
  service:
    type: NodePort
    nodePort: 30001
    